name: First Workflow
on: workflow_dispatch
# on:
#   push:
#     branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello world"
      - name: second step
        run: echo "Done - bye world"
      - name: third step
        run: |
            echo "one"
            echo "two"
      
  #    - uses: actions/checkout@v3
  #    - name: Azure Login
  #      uses: Azure/login@v1
  #      with: 
  #        cred: '${{ secrest.AZURE_Credentials }}'
  #    - name: SetUp JDK
  #      uses: actions/setup-java@v3
  #      with:
  #        java-version: '11'
  #        distribution: 'temurin'
  #        cache: maven
          
          
        
