name: First Workflow
# on: workflow_distpatch (manually)
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello world"
      
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1
        with: 
          cred: '${{ secrest.AZURE_Credentials }}'
      - name: SetUp JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
          
        
